In [ ]:
#Numpy Array Basics
# importing numpy #pip install numpy # conda install numpy
import numpy as np  # numerical python
#import array  #alias  #include<stdio.h> include <math.h>     [7,8.5,'sasi']  list , array , series ,dataframe

# Defining 1D array  # scalar   #print()
my1DArray = np.array([9,8,7,6]) # row , list  #1*4 series
print(my1DArray.ndim)

# Defining and printing 2D array #vector
my2DArray = np.array([[1, 2, 3, 4], [2, 4, 9, 16], [4, 8, 18, 32]]) # 3* 4 = 1 matrix 300 *400 = one matrix
print(my2DArray.ndim)

#Defining and printing 3D array # matrix
my3Darray = np.array([[[ 1, 2 , 3 , 4],[ 5 , 6 , 7  ,8]], [[ 1,  2,  3,  4],[ 9, 10, 11, 12]]]) #2*4,2 = 2 matrix
print(my3Darray.ndim)



1
2
3


In [ ]:
cv = my3Darray.ravel()
cv

array([ 1,  2,  3,  4,  5,  6,  7,  8,  1,  2,  3,  4,  9, 10, 11, 12])

In [ ]:
my3Darray

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 1,  2,  3,  4],
        [ 9, 10, 11, 12]]])

In [ ]:
a = np.arange(5,100,5)
a

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
       90, 95])

In [ ]:
b = np.linspace(1,10,250)
b

array([ 1.        ,  1.03614458,  1.07228916,  1.10843373,  1.14457831,
        1.18072289,  1.21686747,  1.25301205,  1.28915663,  1.3253012 ,
        1.36144578,  1.39759036,  1.43373494,  1.46987952,  1.5060241 ,
        1.54216867,  1.57831325,  1.61445783,  1.65060241,  1.68674699,
        1.72289157,  1.75903614,  1.79518072,  1.8313253 ,  1.86746988,
        1.90361446,  1.93975904,  1.97590361,  2.01204819,  2.04819277,
        2.08433735,  2.12048193,  2.15662651,  2.19277108,  2.22891566,
        2.26506024,  2.30120482,  2.3373494 ,  2.37349398,  2.40963855,
        2.44578313,  2.48192771,  2.51807229,  2.55421687,  2.59036145,
        2.62650602,  2.6626506 ,  2.69879518,  2.73493976,  2.77108434,
        2.80722892,  2.84337349,  2.87951807,  2.91566265,  2.95180723,
        2.98795181,  3.02409639,  3.06024096,  3.09638554,  3.13253012,
        3.1686747 ,  3.20481928,  3.24096386,  3.27710843,  3.31325301,
        3.34939759,  3.38554217,  3.42168675,  3.45783133,  3.49

In [ ]:

 v = np.random.randint(256, size=(4, 7), dtype=np.int16)
 v

array([[185, 157,  29,  78, 222, 121, 187],
       [253, 185,  55, 177, 137, 240,  19],
       [ 69, 232, 188, 158,  70, 241,  66],
       [188,  61, 148,  10, 120,  60, 212]], dtype=int16)

In [ ]:
v[0:2,0:2] # start , end-1

array([[185, 157],
       [253, 185]], dtype=int16)

In [ ]:
v[1:3,2:4]

array([[ 55, 177],
       [188, 158]], dtype=int16)

In [ ]:
e  = np.empty((3,2))
e

array([[4.75277981e-310, 0.00000000e+000],
       [6.61897606e-310, 6.61903928e-310],
       [6.61897605e-310, 6.61903928e-310]])

In [ ]:
c = np.random.rand(5,7)
c

array([[0.33426575, 0.63238319, 0.45754158, 0.73345806, 0.38298316,
        0.5685472 , 0.20070938],
       [0.24764553, 0.86079052, 0.67075051, 0.03410221, 0.21065621,
        0.52338463, 0.97992128],
       [0.04233971, 0.81782292, 0.93367424, 0.83682234, 0.53208637,
        0.71311977, 0.14844606],
       [0.69078481, 0.9406113 , 0.92597449, 0.81699835, 0.47049945,
        0.53726964, 0.51374983],
       [0.02291184, 0.0406957 , 0.73830016, 0.45286213, 0.64874535,
        0.66852979, 0.19030076]])

In [ ]:
c.ndim

2

In [ ]:
c.shape

(5, 7)

In [ ]:
c.size

35

In [ ]:
c.dtype

dtype('float64')

In [ ]:
c.itemsize

8

In [ ]:
d = c.reshape(1,35)  # 1 *35, 35 *1 , 7 *5 , 5 *7

In [ ]:
d.ndim

2

In [ ]:
t = np.empty((10,3))
t.ndim

2

In [ ]:
t

array([[4.75277983e-310, 0.00000000e+000, 0.00000000e+000],
       [2.71597376e-237, 0.00000000e+000, 0.00000000e+000],
       [3.41358806e-046, 0.00000000e+000, 0.00000000e+000],
       [8.11465590e-023, 0.00000000e+000, 0.00000000e+000],
       [2.71597376e-237, 0.00000000e+000, 0.00000000e+000],
       [3.41358806e-046, 0.00000000e+000, 0.00000000e+000],
       [8.11465590e-023, 0.00000000e+000, 0.00000000e+000],
       [2.71597376e-237, 0.00000000e+000, 0.00000000e+000],
       [3.41358806e-046, 0.00000000e+000, 0.00000000e+000],
       [8.11465590e-023, 6.61903924e-310, 6.61903239e-310]])

In [ ]:
r

array([4.75277983e-310, 0.00000000e+000, 0.00000000e+000, 2.71597376e-237,
       0.00000000e+000, 0.00000000e+000, 3.41358806e-046, 0.00000000e+000,
       0.00000000e+000, 8.11465590e-023, 0.00000000e+000, 0.00000000e+000,
       2.71597376e-237, 0.00000000e+000, 0.00000000e+000, 3.41358806e-046,
       0.00000000e+000, 0.00000000e+000, 8.11465590e-023, 0.00000000e+000,
       0.00000000e+000, 2.71597376e-237, 0.00000000e+000, 0.00000000e+000,
       3.41358806e-046, 0.00000000e+000, 0.00000000e+000, 8.11465590e-023,
       6.61903924e-310, 6.61903239e-310])

In [ ]:
r = t.flatten()
r.ndim

1

In [ ]:
a = np.array([6,7.6,8,9,6,4,0,'jgjh',True])
type(a)

numpy.ndarray

In [ ]:
a.ndim

1

In [ ]:
my2DArray.ndim  # vector

2

In [ ]:
a = [6]
s = np.array(a)

In [ ]:
s.ndim # scalar = 1 dim , vector = 2 dim , matrix 3 dim , tensor = multi 7d

1

[7,8.0,9.7]  array ;  series ; 1 row;  record

In [ ]:
my2DArray.ndim

2

In [ ]:
my2DArray.shape

(3, 4)

In [ ]:
my1DArray.shape #(4,)   #.reshape

(4,)

In [ ]:
a = [1,6,7.6,"sdas","jhgjg"]

In [ ]:
s = np.array([5,7,9,9,5,6,4,7,9,8,7,6])
for i in s:
 print(i*7)

35
49
63
63
35
42
28
49
63
56
49
42


In [ ]:
ss = np.array([5,7,9])
vv = np.array([8,9,7])
yy = np.array([8,7,6])

In [ ]:
type(ss)

numpy.ndarray

In [ ]:
ss.shape

(3,)

In [ ]:
ss.reshape(3,12)

array([[5],
       [7],
       [9]])

In [ ]:
c = np.concatenate((ss,vv,yy))

In [ ]:
c

array([5, 7, 9, 8, 9, 7, 8, 7, 6])

In [ ]:
c.ndim

1

In [ ]:
d = np.vstack((ss,vv,yy))

In [ ]:
d

array([[5, 7, 9],
       [8, 9, 7],
       [8, 7, 6]])

In [ ]:
d.ndim

2

In [ ]:
u = np.array_split(c,5)

In [ ]:
u

[array([5, 7]), array([9]), array([8]), array([9]), array([7])]

In [ ]:
s.reshape(4,3)

array([[5, 7, 9],
       [9, 5, 6],
       [4, 7, 9],
       [8, 7, 6]])

In [ ]:
b = np.where (u == 7)

In [ ]:
b

(array([], dtype=int64),)

In [ ]:
import numpy as np

In [ ]:
zeros1 = np.zeros((2,4,5))

In [ ]:
zeros1

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [ ]:
a.ndim

AttributeError: ignored

In [ ]:
b = np.array(a)

In [ ]:
b.ndim    # []

1

In [ ]:
b.dtype

dtype('<U32')

In [ ]:
s = [4,5,'sa'] #series , list , array

In [ ]:
type(s)

list

In [ ]:
 v = np.array(s)

In [ ]:
type(v)

numpy.ndarray

In [ ]:
# Print out memory address
print(my2DArray.data)
print(my2DArray)

# Print the shape of array
print(my2DArray.shape)

# Print out the data type of the array
print(my2DArray.dtype)


[[ 1  2  3  4]
 [ 2  4  9 16]
 [ 4  8 18 32]]
(3, 4)
int64


In [ ]:
s1 =np.random.random((2,4,5))

In [ ]:
s1

array([[[0.50067679, 0.28794721, 0.39911225, 0.84141237, 0.7416266 ],
        [0.23374673, 0.40213509, 0.86035117, 0.20188524, 0.9879639 ],
        [0.97984607, 0.92656542, 0.35068385, 0.8236853 , 0.34768771],
        [0.96195113, 0.24683416, 0.79529732, 0.53609071, 0.43265814]],

       [[0.13166902, 0.25075013, 0.96403689, 0.68774745, 0.68196857],
        [0.00179764, 0.52139818, 0.43788341, 0.53573047, 0.41488388],
        [0.3298231 , 0.88994239, 0.73135779, 0.87543662, 0.8684881 ],
        [0.44863561, 0.13301629, 0.92036444, 0.31390681, 0.45653721]]])

In [ ]:
emptyArray = np.empty((3,2))

In [ ]:
emptyArray

array([[5.03713268e-310, 0.00000000e+000],
       [4.59237527e-072, 3.30146360e-258],
       [7.29543846e+175, 2.20892684e+161]])

In [ ]:
from google.colab import files
data = files.upload()

Saving pima-indians-diabetes.csv to pima-indians-diabetes.csv


In [ ]:
data

{'pima-indians-diabetes.csv': b'6,148,72,35,0,33.6,0.627,50,1\n1,85,66,29,0,26.6,0.351,31,0\n8,183,64,0,0,23.3,0.672,32,1\n1,89,66,23,94,28.1,0.167,21,0\n0,137,40,35,168,43.1,2.288,33,1\n5,116,74,0,0,25.6,0.201,30,0\n3,78,50,32,88,31.0,0.248,26,1\n10,115,0,0,0,35.3,0.134,29,0\n2,197,70,45,543,30.5,0.158,53,1\n8,125,96,0,0,0.0,0.232,54,1\n4,110,92,0,0,37.6,0.191,30,0\n10,168,74,0,0,38.0,0.537,34,1\n10,139,80,0,0,27.1,1.441,57,0\n1,189,60,23,846,30.1,0.398,59,1\n5,166,72,19,175,25.8,0.587,51,1\n7,100,0,0,0,30.0,0.484,32,1\n0,118,84,47,230,45.8,0.551,31,1\n7,107,74,0,0,29.6,0.254,31,1\n1,103,30,38,83,43.3,0.183,33,0\n1,115,70,30,96,34.6,0.529,32,1\n3,126,88,41,235,39.3,0.704,27,0\n8,99,84,0,0,35.4,0.388,50,0\n7,196,90,0,0,39.8,0.451,41,1\n9,119,80,35,0,29.0,0.263,29,1\n11,143,94,33,146,36.6,0.254,51,1\n10,125,70,26,115,31.1,0.205,41,1\n7,147,76,0,0,39.4,0.257,43,1\n1,97,66,15,140,23.2,0.487,22,0\n13,145,82,19,110,22.2,0.245,57,0\n5,117,92,0,0,34.1,0.337,38,0\n5,109,75,26,0,36.0,0.546,60,0

In [ ]:
my2DArray.shape

(3, 4)

In [ ]:
print(my2DArray.strides)

(32, 8)


what is stride of array?  It is the number of locations in memory between
beginnings of successive array elements, measured in bytes or in units of the
size of the array's elements
"""


In [ ]:
#Array using numpy built-in functions
# Array of ones
ones = np.ones((4,3,4),dtype = int) # row , colum, no of matrix
print(ones)

# Array of zeros
zeros = np.zeros((5,3,4),dtype=np.int16) # 2, 50,500,578687669696
print(zeros)

# Array with random values
s =np.random.random((2,2))

# Empty array
emptyArray = np.empty((3,2))
print(emptyArray)


# Full array
fullArray = np.full((2,2),7)
print(fullArray)

# Array of evenly-spaced values
evenSpacedArray = np.arange(0,26,5)  # 0,10,0.02  start , end-1 , steps
print(evenSpacedArray)

# Array of evenly-spaced values
evenSpacedArray2 = np.linspace(0,2,99) # (100, 2200, 35) # start range , end range , count of values
print(evenSpacedArray2)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
[[5.03713260e-310 0.00000000e+000]
 [6.62686607e-310 2.93487123e-130]
 [3.38983205e+208 6.25593821e-310]]
[[7 7]
 [7 7]]
[ 0  5 10 15 20 25]
[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93

In [ ]:
zeros = np.zeros((5,3,4),dtype=int) # 2, 50,500,578687669696  # 70, 5671253, 4   4.80 4.4567457568
print(zeros)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [ ]:
zero = np.zeros((3,2,4))

In [ ]:
zero

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
zeros

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int16)

In [ ]:
emptyArray = np.empty((3,2))
print(emptyArray)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
s

array([[0.3510922 , 0.57800863],
       [0.10633287, 0.5591529 ]])

In [ ]:
emptyArray

array([[4.67020372e-310, 4.94065646e-324],
       [4.94065646e-324, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000]])

In [ ]:
s

array([[0.19097417, 0.34202638],
       [0.58400162, 0.64276739]])

In [ ]:
r = np.array([[[5,3,9,10],[6,7,8,3],[7,5,7,9]],[[7,6,5,9],[6,7,8,6],[4,7,8,9]]],dtype = complex) #3 *4 , 1*4



r.ndim # 3
r.shape  #67+-9kly
r



array([[[ 5.+0.j,  3.+0.j,  9.+0.j, 10.+0.j],
        [ 6.+0.j,  7.+0.j,  8.+0.j,  3.+0.j],
        [ 7.+0.j,  5.+0.j,  7.+0.j,  9.+0.j]],

       [[ 7.+0.j,  6.+0.j,  5.+0.j,  9.+0.j],
        [ 6.+0.j,  7.+0.j,  8.+0.j,  6.+0.j],
        [ 4.+0.j,  7.+0.j,  8.+0.j,  9.+0.j]]])

In [ ]:

i = 0
j = 1
k = 1
r[i,j,k]

(7+0j)

In [ ]:
t = np.array([[5,3,9,10],[6,7,8,3],[7,5,7,9]]) # matrix
t

array([[ 5,  3,  9, 10],
       [ 6,  7,  8,  3],
       [ 7,  5,  7,  9]])

In [ ]:
t[1:3,2:4] # end-1

array([[8, 3],
       [7, 9]])

In [ ]:
t[1:3,1:3]

array([[7, 8],
       [5, 7]])

In [ ]:
y = np.array([5,3,9,10]) #series
y

array([ 5,  3,  9, 10])

In [ ]:
r.ndim

3

In [ ]:
r.shape

(3, 4)

In [ ]:
r[0,::,]

array([[ 5.+0.j,  3.+0.j,  9.+0.j, 10.+0.j],
       [ 6.+0.j,  7.+0.j,  8.+0.j,  3.+0.j],
       [ 7.+0.j,  5.+0.j,  7.+0.j,  9.+0.j]])

In [ ]:
t % 2 == 0

array([[False, False, False,  True],
       [ True, False,  True, False],
       [False, False, False, False]])

In [ ]:
t[t %2 == 0] #show s the value whever the condition is true

array([10,  6,  8])

In [ ]:
t

array([[ 5,  3,  9, 10],
       [ 6,  7,  8,  3],
       [ 7,  5,  7,  9]])

In [ ]:
my_indeces = [2,1]

In [ ]:
t[my_indeces]

array([[7, 5, 7, 9],
       [6, 7, 8, 3]])

In [ ]:
# Broadcasting in NumPy
#Scalar and One-Dimensional Array
import array

In [ ]:
a = np.array([1, 2, 3])

In [ ]:
b = np.array([8,7,9])

In [ ]:
c = a + b

In [ ]:
c

array([ 9,  9, 12])

In [ ]:
#Scalar and Two-Dimensional Array

In [ ]:
k = np.array([5,3,6,7,9])
j=np.array([4,2,6,9,8])

In [ ]:
g = k+j

In [ ]:
g

array([ 9,  5, 12, 16, 17])

array([[ 63, 320,  83],
       [ 77, 484, 102],
       [ 84, 248, 117]])