In [ ]:
import numpy as np


array = collection of related items

 conceptual array = [ 2,'india', 'Asia', 148.52, True]

 technical array = [2,5,6,9,7] # collection of similar data types

In [ ]:
 a = [10,5]

In [ ]:
type(a)

list

1.create a numpy array

In [ ]:
a = np.array([4,8,9])

b = np.array([9,8,5])
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
type(a)

numpy.ndarray

In [ ]:
a.ndim

1

In [ ]:
c = np.arange(2,2000,500) # start , end-1 , steps
print(c)

[   2  502 1002 1502]


In [ ]:
d = np.linspace(4,6,25,dtype =float)
print(d)

[4.         4.08333333 4.16666667 4.25       4.33333333 4.41666667
 4.5        4.58333333 4.66666667 4.75       4.83333333 4.91666667
 5.         5.08333333 5.16666667 5.25       5.33333333 5.41666667
 5.5        5.58333333 5.66666667 5.75       5.83333333 5.91666667
 6.        ]


important functions to check on handson :
ndim,
shape,
size,
Dtype,
itemsize,
Reshape

In [ ]:
# converting the dimensionality using numpy  2d to 1d
e = np.array([[3,4,5],[8,9,8],[9,8,6]])
f = e.flatten()
print(f.ndim)

1


In [ ]:
e


array([[3, 4, 5],
       [8, 9, 8],
       [9, 8, 6]])

In [ ]:
f

array([3, 4, 5, 8, 9, 8, 9, 8, 6])

In [ ]:
e.ndim

2

In [ ]:
g = e.ravel() #2d or 3d to 1 d
print(g)

[3 4 5 8 9 8 9 8 6]


In [ ]:
print(e)

[[3 4 5]
 [8 9 8]
 [9 8 6]]


In [ ]:
e.reshape(1,9)

array([[3, 4, 5, 8, 9, 8, 9, 8, 6]])

In [ ]:
h = e.reshape(9,1)
print(h)

[[3]
 [4]
 [5]
 [8]
 [9]
 [8]
 [9]
 [8]
 [6]]


In [ ]:
h.T

array([[3, 4, 5, 8, 9, 8, 9, 8, 6]])

In [ ]:
#insertion and deletion of array

arr = np.array([9,6,5,4,9])
arr = np.insert(arr,2,10)
arr

array([ 9,  6, 10,  5,  4,  9])

In [ ]:
arr = np.delete(arr,2) # arrayvalue , index , value to insert

In [ ]:
arr

array([9, 6, 5, 4, 9])

\sum(),min(),max(),mean(),median(),corrcoef(),np.std(b)

In [ ]:
# find the index of a value
arr1 = np.arange(10)
index = np.where (arr1 == 2)
print(index)

(array([2]),)


In [ ]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr3 = np.array([7,8,9,5,4,0,1,3,7])
#ss = print(arr3.sort())

In [ ]:
arr3.sort()
print("enter the sorted array:",arr3)

enter the sorted array: [0 1 3 4 5 7 7 8 9]


In [ ]:
# array broadcasting : braodcasting : applying mathematical functions # +,-,*,%,/ , //

x = np.ones((4,3))
y = np.random.random((4,3))
print(x+y)

[[1.84006104 1.13151233 1.97479981]
 [1.99660583 1.7628056  1.05767206]
 [1.73782619 1.37098458 1.86448662]
 [1.0632165  1.79704877 1.67952744]]


In [ ]:
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
y

array([[0.84006104, 0.13151233, 0.97479981],
       [0.99660583, 0.7628056 , 0.05767206],
       [0.73782619, 0.37098458, 0.86448662],
       [0.0632165 , 0.79704877, 0.67952744]])

In [ ]:
print(x-y)

[[0.15993896 0.86848767 0.02520019]
 [0.00339417 0.2371944  0.94232794]
 [0.26217381 0.62901542 0.13551338]
 [0.9367835  0.20295123 0.32047256]]


exercise part :Aggregation functions:
 sum(),
 min(),
 max(),
 cumsum(),
 mean(),
 median(),
 corrcoef(),
 std(),
 np.sin(),
 np.cos()

In [ ]:
print(arr[arr>5])

[9 6 9]


In [ ]:
arr.T

array([9, 6, 5, 4, 9])

In [ ]:
#altering the array
a3 = np.array([5,7,9,4,7])
a3 = np.insert(a3,4,47) #(arr,index(location),axes(value))
a3

array([ 5,  7,  9,  4, 47,  7])

In [ ]:
a3 = np.delete(a3,1)
a3

array([ 5,  9,  4, 47,  7])

In [ ]:
#retrieve diagonal from an array
a4 = np.arange(27).reshape(3,3,3) # arange (27 ) = arrange values between 0 to 26
a4



array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
print(a4.diagonal(axis1=1,axis2=2))

[[ 0  4  8]
 [ 9 13 17]
 [18 22 26]]
