<a href="https://colab.research.google.com/github/bshriselvamkumar/AI-ML-DL-Training/blob/main/Selvam_Lasso_Regularisation_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
from sklearn.datasets import load_diabetes

In [18]:
df = load_diabetes()

In [8]:
from google.colab import files
d = files.upload()

In [19]:
df.data

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [20]:
df.target

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
x_train, x_test, y_train, y_test = train_test_split(df.data,df.target, test_size = 0.2, random_state= 34)

In [23]:
from sklearn.linear_model import Lasso

In [26]:
model = Lasso(alpha = 0.2)

In [27]:
model.fit(x_train, y_train)

Lasso(alpha=0.2)

In [42]:
ypredict = model.predict(x_test)

In [43]:
ypredict

array([153.49175179,  74.9982868 , 186.15721316, 105.90335603,
       151.85531358,  87.0567848 , 240.01994456, 168.28331389,
       129.86903582,  91.62210528, 103.8816855 , 116.73950518,
       175.07156145, 114.06178822, 217.7370765 , 109.73908474,
       123.75431336, 129.81879226, 253.05175001, 169.87476006,
       159.14787097, 127.17581341, 119.30762471, 173.5466583 ,
       150.31935508, 119.58631869, 181.35954448, 122.84353809,
       245.14073593,  91.11495071, 197.13796978, 128.23933794,
       168.4754206 , 178.32880511, 118.10706099, 190.75665938,
       191.53993131,  63.54215107, 112.81294045, 125.80689358,
       118.63653013, 142.32245325, 182.95190286, 182.52964553,
       199.53714835, 148.84571589, 153.60013045, 215.37025278,
       158.59339597, 121.44988523,  65.38483001, 152.39879662,
        82.89449533,  64.57279405, 167.41977297, 189.93208654,
        99.25750608, 169.5304676 , 172.01727133, 105.70500983,
       183.77661184, 176.43258611, 137.02293297, 105.26

In [44]:
y_test

array([262.,  65.,  67.,  80., 154.,  42., 336.,  91.,  51., 114.,  55.,
        84., 122., 128., 280.,  31.,  64., 109., 273., 265., 118.,  60.,
       127.,  70., 155.,  97., 174., 140., 220.,  72., 150., 107., 178.,
       140., 162., 164., 220.,  48., 118., 144., 183.,  81., 129., 262.,
       288., 230., 185., 257., 113.,  89.,  57., 142., 158.,  63., 225.,
       196.,  88., 311., 147.,  64.,  84.,  90.,  50.,  72., 131., 104.,
       275.,  91., 210.,  52., 124.,  95.,  69.,  85., 172., 292., 168.,
       160., 202., 199., 144., 221., 102., 179.,  63.,  94.,  47., 121.,
       103.])

In [45]:
error = ypredict - y_test

In [46]:
error

array([-108.50824821,    9.9982868 ,  119.15721316,   25.90335603,
         -2.14468642,   45.0567848 ,  -95.98005544,   77.28331389,
         78.86903582,  -22.37789472,   48.8816855 ,   32.73950518,
         53.07156145,  -13.93821178,  -62.2629235 ,   78.73908474,
         59.75431336,   20.81879226,  -19.94824999,  -95.12523994,
         41.14787097,   67.17581341,   -7.69237529,  103.5466583 ,
         -4.68064492,   22.58631869,    7.35954448,  -17.15646191,
         25.14073593,   19.11495071,   47.13796978,   21.23933794,
         -9.5245794 ,   38.32880511,  -43.89293901,   26.75665938,
        -28.46006869,   15.54215107,   -5.18705955,  -18.19310642,
        -64.36346987,   61.32245325,   53.95190286,  -79.47035447,
        -88.46285165,  -81.15428411,  -31.39986955,  -41.62974722,
         45.59339597,   32.44988523,    8.38483001,   10.39879662,
        -75.10550467,    1.57279405,  -57.58022703,   -6.06791346,
         11.25750608, -141.4695324 ,   25.01727133,   41.70500

In [37]:
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [47]:
mae = mean_absolute_error(y_test, ypredict)

In [48]:
mse = mean_squared_error(y_test, ypredict)

In [49]:
mae

46.70424627225331

In [50]:
mse

3254.350010434912