<a href="https://colab.research.google.com/github/bshriselvamkumar/AI-ML-DL-Training/blob/main/Shriselvam_Lasso_Ridge_ElasticNet_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn.datasets import load_diabetes

In [3]:
df = load_diabetes()

In [4]:
df.data

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [5]:
df.target

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
x_train, x_test, y_train, y_test = train_test_split(df.data,df.target, test_size = 0.2, random_state= 24)

In [8]:
from sklearn.linear_model import Lasso

In [9]:
from sklearn.linear_model import Ridge

In [10]:
from sklearn.linear_model import ElasticNet

In [11]:
model = Lasso(alpha = 1.2)

In [12]:
model2 = Ridge(alpha = 1.2)

In [13]:
model3 = ElasticNet(alpha = 1.2)

In [14]:
model.fit(x_train,y_train)

Lasso(alpha=1.2)

In [15]:
model2.fit(x_train,y_train)

Ridge(alpha=1.2)

In [16]:
model3.fit(x_train,y_train)

ElasticNet(alpha=1.2)

In [17]:
ypredict = model.predict(x_test)

In [18]:
ypredict2 = model2.predict(x_test)

In [19]:
ypredict3 = model3.predict(x_test)

In [20]:
ypredict

array([118.75472021, 120.94638762, 167.74301083, 139.03653486,
       144.79728838, 145.06269667, 152.54424311, 150.49396627,
       138.81826871, 125.61370567, 122.7535253 , 158.96419224,
       166.48579192, 195.68284352, 126.26250554, 171.09707367,
       133.74755846, 124.5487017 , 129.86475566, 112.78803722,
       158.47778601, 144.85748214, 175.46435371, 129.15904497,
       152.1289775 , 135.39830107, 145.94524242, 146.70827938,
       194.37379778, 163.1028343 , 125.82017433, 134.11208757,
       156.22998248, 163.14520388, 186.16896815, 123.51786419,
       159.50504111, 157.5470078 , 159.23880611, 158.13882093,
       143.72465634, 171.42366621, 139.61260466, 121.83426901,
       117.82126222, 166.91965638, 111.12329256, 158.60270635,
       147.57508178, 152.25766795, 124.62317307, 163.97956917,
       169.02323772, 142.81321582, 166.02448645, 153.65498746,
       153.1865931 , 137.75631992, 130.96471694, 117.92934891,
       181.16316024, 158.67616331, 170.30362841, 161.18

In [21]:
ypredict2

array([106.22127595,  95.19931831, 161.83445789, 135.21653419,
       126.5773567 , 163.30129481, 148.05312349, 130.37889866,
       131.38769313, 129.77717879, 109.46689062, 144.00968096,
       157.61233266, 203.76212772, 108.96470605, 173.99098489,
       136.08740459,  87.00427836, 138.8973115 ,  87.23363201,
       167.22281467, 144.25912734, 169.51701947, 126.09098685,
       173.71568775, 132.517809  , 184.10912115, 143.6797843 ,
       194.31804212, 160.73277374,  99.9435506 ,  98.67272217,
       159.29145166, 164.96550063, 192.35979532, 102.09360707,
       153.44990372, 180.40510757, 164.80247185, 164.91360943,
       142.63793247, 171.97817375, 129.4667749 , 121.09739427,
       101.57942257, 169.61097862,  92.3501468 , 193.35455973,
       175.42997217, 149.00067905, 108.68561415, 161.94774901,
       193.84666488, 125.47067553, 145.41379832, 168.7263118 ,
       138.9927859 , 130.77479774, 116.86805969,  94.63442585,
       178.38683193, 173.98669476, 187.41783466, 144.87

In [22]:
ypredict3

array([154.27937513, 154.16900181, 154.92043044, 154.69788339,
       154.51535196, 154.94486031, 154.85518115, 154.55264904,
       154.63881766, 154.57998948, 154.40389228, 154.72199664,
       154.85002016, 155.45294423, 154.3944686 , 155.1355217 ,
       154.73781806, 154.0700122 , 154.6915835 , 154.09060054,
       155.07905803, 154.70716191, 155.00635061, 154.55078823,
       155.11115701, 154.64063745, 155.1534702 , 154.80343702,
       155.27459665, 154.84354621, 154.23532533, 154.20388004,
       154.97705626, 154.96721959, 155.30946182, 154.21460623,
       154.84322494, 155.1817444 , 155.0264343 , 154.95559455,
       154.79887095, 155.0311925 , 154.5572179 , 154.46961489,
       154.29630126, 155.02849677, 154.13311022, 155.38596811,
       155.17851506, 154.86160109, 154.34161181, 154.87414181,
       155.30890595, 154.59097315, 154.69091065, 155.09574854,
       154.75872751, 154.5587116 , 154.51586828, 154.14003821,
       155.12395115, 155.12956159, 155.29087106, 154.70

In [23]:
y_test

array([ 89.,  59., 128.,  53., 168., 206., 202.,  59.,  88., 158., 138.,
       172., 147., 295.,  71., 196., 118.,  65., 214.,  48., 259.,  49.,
        91.,  72., 257., 199., 189.,  74., 128.,  70.,  52.,  39., 209.,
       283., 259., 114.,  95., 129., 235., 170.,  51., 180.,  68.,  49.,
        78., 202.,  99., 292., 120., 139., 200., 175., 249.,  88.,  95.,
       179.,  96., 185.,  42.,  37., 151., 311., 222., 276.,  98.,  79.,
        45.,  75.,  84., 192., 141.,  71., 275.,  59.,  85., 144., 191.,
       202.,  96., 243., 191., 143., 101., 100., 265., 172., 190.,  60.,
        42.])

In [24]:
error = ypredict - y_test

In [25]:
error2 = ypredict2 - y_test

In [26]:
error3 = ypredict3 - y_test

In [27]:
error

array([  29.75472021,   61.94638762,   39.74301083,   86.03653486,
        -23.20271162,  -60.93730333,  -49.45575689,   91.49396627,
         50.81826871,  -32.38629433,  -15.2464747 ,  -13.03580776,
         19.48579192,  -99.31715648,   55.26250554,  -24.90292633,
         15.74755846,   59.5487017 ,  -84.13524434,   64.78803722,
       -100.52221399,   95.85748214,   84.46435371,   57.15904497,
       -104.8710225 ,  -63.60169893,  -43.05475758,   72.70827938,
         66.37379778,   93.1028343 ,   73.82017433,   95.11208757,
        -52.77001752, -119.85479612,  -72.83103185,    9.51786419,
         64.50504111,   28.5470078 ,  -75.76119389,  -11.86117907,
         92.72465634,   -8.57633379,   71.61260466,   72.83426901,
         39.82126222,  -35.08034362,   12.12329256, -133.39729365,
         27.57508178,   13.25766795,  -75.37682693,  -11.02043083,
        -79.97676228,   54.81321582,   71.02448645,  -25.34501254,
         57.1865931 ,  -47.24368008,   88.96471694,   80.92934

In [28]:
error2

array([  17.22127595,   36.19931831,   33.83445789,   82.21653419,
        -41.4226433 ,  -42.69870519,  -53.94687651,   71.37889866,
         43.38769313,  -28.22282121,  -28.53310938,  -27.99031904,
         10.61233266,  -91.23787228,   37.96470605,  -22.00901511,
         18.08740459,   22.00427836,  -75.1026885 ,   39.23363201,
        -91.77718533,   95.25912734,   78.51701947,   54.09098685,
        -83.28431225,  -66.482191  ,   -4.89087885,   69.6797843 ,
         66.31804212,   90.73277374,   47.9435506 ,   59.67272217,
        -49.70854834, -118.03449937,  -66.64020468,  -11.90639293,
         58.44990372,   51.40510757,  -70.19752815,   -5.08639057,
         91.63793247,   -8.02182625,   61.4667749 ,   72.09739427,
         23.57942257,  -32.38902138,   -6.6498532 ,  -98.64544027,
         55.42997217,   10.00067905,  -91.31438585,  -13.05225099,
        -55.15333512,   37.47067553,   50.41379832,  -10.2736882 ,
         42.9927859 ,  -54.22520226,   74.86805969,   57.63442

In [29]:
error3

array([  65.27937513,   95.16900181,   26.92043044,  101.69788339,
        -13.48464804,  -51.05513969,  -47.14481885,   95.55264904,
         66.63881766,   -3.42001052,   16.40389228,  -17.27800336,
          7.85002016, -139.54705577,   83.3944686 ,  -40.8644783 ,
         36.73781806,   89.0700122 ,  -59.3084165 ,  106.09060054,
       -103.92094197,  105.70716191,   64.00635061,   82.55078823,
       -101.88884299,  -44.35936255,  -33.8465298 ,   80.80343702,
         27.27459665,   84.84354621,  102.23532533,  115.20388004,
        -54.02294374, -128.03278041, -103.69053818,   40.21460623,
         59.84322494,   26.1817444 ,  -79.9735657 ,  -15.04440545,
        103.79887095,  -24.9688075 ,   86.5572179 ,  105.46961489,
         76.29630126,  -46.97150323,   55.13311022, -136.61403189,
         35.17851506,   15.86160109,  -45.65838819,  -20.12585819,
        -93.69109405,   66.59097315,   59.69091065,  -23.90425146,
         58.75872751,  -30.4412884 ,  112.51586828,  117.14003

In [30]:
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [31]:
mae = mean_absolute_error(y_test, ypredict)
mae2 = mean_absolute_error(y_test, ypredict2)
mae3 = mean_absolute_error(y_test, ypredict3)

In [32]:
mse = mean_squared_error(y_test, ypredict)
mse2 = mean_squared_error(y_test, ypredict2)
mse3 = mean_squared_error(y_test, ypredict3)

In [33]:
mae

56.57995226255275

In [34]:
mae2

50.74031111636374

In [35]:
mae3

65.80139401743325

In [36]:
mse

4190.332423729776

In [37]:
mse2

3465.787924055205

In [38]:
mse3

5668.385511541044